
// This file has been generated by the GUI designer. Do not modify.
namespace MonoReports.Gui.Widgets
{
	public partial class MonoreportsDesignerControl
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.VBox mainVbox;
		private global::Gtk.Toolbar mainToolbar;
		private global::Gtk.HBox contentHbox;
		private global::Gtk.HPaned mainHPaned;
		private global::MonoReports.Gui.Widgets.MainDesignView maindesignview1;
		private global::Gtk.VPaned rightVPaned;
		private global::MonoReports.Gui.Widgets.ReportExplorer reportExplorer;
		private global::PropertyGrid.PropertyGrid mainPropertygrid;
		private global::Gtk.Statusbar bottomStatusbar;
		private global::Gtk.Label StatusBarLabel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoReports.Gui.Widgets.MonoreportsDesignerControl
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "MonoReports.Gui.Widgets.MonoreportsDesignerControl";
			// Container child MonoReports.Gui.Widgets.MonoreportsDesignerControl.Gtk.Container+ContainerChild
			this.mainVbox = new global::Gtk.VBox ();
			this.mainVbox.Name = "mainVbox";
			this.mainVbox.Spacing = -1;
			// Container child mainVbox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='mainToolbar'/></ui>");
			this.mainToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/mainToolbar")));
			this.mainToolbar.Name = "mainToolbar";
			this.mainToolbar.ShowArrow = false;
			this.mainToolbar.IconSize = ((global::Gtk.IconSize)(1));
			this.mainVbox.Add (this.mainToolbar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.mainVbox [this.mainToolbar]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child mainVbox.Gtk.Box+BoxChild
			this.contentHbox = new global::Gtk.HBox ();
			this.contentHbox.Name = "contentHbox";
			this.contentHbox.Spacing = 6;
			// Container child contentHbox.Gtk.Box+BoxChild
			this.mainHPaned = new global::Gtk.HPaned ();
			this.mainHPaned.CanFocus = true;
			this.mainHPaned.Name = "mainHPaned";
			this.mainHPaned.Position = 735;
			// Container child mainHPaned.Gtk.Paned+PanedChild
			this.maindesignview1 = new global::MonoReports.Gui.Widgets.MainDesignView ();
			this.maindesignview1.Events = ((global::Gdk.EventMask)(256));
			this.maindesignview1.Name = "maindesignview1";
			this.mainHPaned.Add (this.maindesignview1);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.mainHPaned [this.maindesignview1]));
			w4.Resize = false;
			// Container child mainHPaned.Gtk.Paned+PanedChild
			this.rightVPaned = new global::Gtk.VPaned ();
			this.rightVPaned.CanFocus = true;
			this.rightVPaned.Name = "rightVPaned";
			this.rightVPaned.Position = 291;
			// Container child rightVPaned.Gtk.Paned+PanedChild
			this.reportExplorer = new global::MonoReports.Gui.Widgets.ReportExplorer ();
			this.reportExplorer.Name = "reportExplorer";
			this.rightVPaned.Add (this.reportExplorer);
			global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.rightVPaned [this.reportExplorer]));
			w5.Resize = false;
			// Container child rightVPaned.Gtk.Paned+PanedChild
			this.mainPropertygrid = new global::PropertyGrid.PropertyGrid ();
			this.mainPropertygrid.Name = "mainPropertygrid";
			this.mainPropertygrid.ShowToolbar = false;
			this.mainPropertygrid.ShowHelp = false;
			this.rightVPaned.Add (this.mainPropertygrid);
			this.mainHPaned.Add (this.rightVPaned);
			global::Gtk.Paned.PanedChild w7 = ((global::Gtk.Paned.PanedChild)(this.mainHPaned [this.rightVPaned]));
			w7.Resize = false;
			this.contentHbox.Add (this.mainHPaned);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.contentHbox [this.mainHPaned]));
			w8.Position = 0;
			this.mainVbox.Add (this.contentHbox);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.mainVbox [this.contentHbox]));
			w9.Position = 1;
			// Container child mainVbox.Gtk.Box+BoxChild
			this.bottomStatusbar = new global::Gtk.Statusbar ();
			this.bottomStatusbar.Name = "bottomStatusbar";
			this.bottomStatusbar.Spacing = 6;
			// Container child bottomStatusbar.Gtk.Box+BoxChild
			this.StatusBarLabel = new global::Gtk.Label ();
			this.StatusBarLabel.Name = "StatusBarLabel";
			this.bottomStatusbar.Add (this.StatusBarLabel);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.bottomStatusbar [this.StatusBarLabel]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.mainVbox.Add (this.bottomStatusbar);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.mainVbox [this.bottomStatusbar]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.Add (this.mainVbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
			this.mainPropertygrid.Changed += new global::System.EventHandler (this.OnMainPropertygridChanged);
		}
	}
}
